# Generated by Django 6.1.1 on 2026-09-17 11:49

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_answers_textans'),
    ]

    operations = [
        migrations.AddField(
            model_name='answers',
            name='text',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
