# Generated by Django 6.1.1 on 2026-09-17 12:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_answers_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answers',
            name='textans',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answersa', to='api.question'),
        ),
    ]
